import type { NextPage } from 'next';
import Head from 'next/head';
import { dummyMentors } from './dummyMentor';
import MentorList from './mentor-list';

const adminPanel: NextPage = ({}) => {
  return (
    <div>
      <Head>
        <title>Empowered Futures - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative w-full h-screen flex items-center justify-center bg-smoke-2">
        <div className="bg-smoke-4 w-full h-60 absolute top-0 left-0 z-0"></div>
        <div className="bg-light w-2/3 h-5/6 m-auto z-50 rounded-md p-4">
          <h1 className="text-3xl">Dashboard</h1>
          <div className="flex gap-4">
            <div className="bg-gradient-to-r from-cyan-500 to-blue-500 w-60 h-20 rounded-sm flex items-center justify-center">
              <h2 className="text-xl text-light">10 Mentors</h2>
            </div>
            <div className="bg-gradient-to-r from-teal-400 to-green-500 w-60 h-20 rounded-sm flex items-center justify-center">
              <h2 className="text-xl text-light">6 Online</h2>
            </div>
            <div className="bg-gradient-to-r from-amber-400 to-orange-500 w-60 h-20 rounded-sm flex items-center justify-center">
              <h2 className="text-xl text-light">4 Offline</h2>
            </div>
          </div>
          <div>
            <div>
              <div>
                <h4>Mentor Details</h4>
                <input type="text"></input>
                <button>filter</button>
              </div>
              <ul>
                <li>Name</li>
                <li>Email</li>
                <li>Status</li>
              </ul>
              <ul>
                {dummyMentors.map((mentor, index) => (
                  <MentorList
                    name={mentor.name}
                    key={mentor.name}
                    index={index}
                  />
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default adminPanel;
