import type { NextPage } from 'next';
import Head from 'next/head';

const becomeAMentor: NextPage = ({}) => {
  return (
    <div>
      <Head>
        <title>Empowered Futures - Become a Mentor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Become a Mentor placeholder</h1>

      {/* Description of role  */}

      {/* What's in it for you?  */}

      {/* Prerequisite requirements  */}

      {/* Apply button  */}

      {/* Footer */}
    </div>
  );
};

export default becomeAMentor;
