import type { NextPage } from 'next';
import Head from 'next/head';

const becomeAMentee: NextPage = ({}) => {
  return (
    <div>
      <Head>
        <title>Empowered Futures - Become a Mentee </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Become a Mentee placeholder</h1>
    </div>
  );
};

export default becomeAMentee;
