import type { NextPage } from 'next';
import Head from 'next/head';
import RemovableTags from '../components/RemovableTags';

let arr = [
  'tomato',
  'kayak',
  'racecar',
  'woo young woo',
  'tomato',
  'kayak',
  'racecar',
  'woo young woo',
];

const removeTag = (index: number) => {
  arr = arr.filter((tag, i) => i == index);
  console.log(arr)
};

const becomeAMentor: NextPage = ({}) => {
  return (
    <div>
      <Head>
        <title>Empowered Futures - Become a Mentor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Become a Mentor placeholder</h1>
      <RemovableTags tags={arr} removeTag={removeTag} />
    </div>
  );
};

export default becomeAMentor;
