import type { NextPage } from 'next';
import Head from 'next/head';

const becomeAMentor2: NextPage = ({}) => {
  const bullets = [
    [
      `Hosting introductory events geared at meeting your mentees`,
      `Situating your mentees by informing them of our institute's procedural norms and initiatives`,
      `Alerting your mentees to potential adjustment-related obstacles and issuing them with suitable resources to help negate these`,
      `Scheduling follow-ups to gauge your mentees' progress`,
      `Encouraging participation in mentor-mentee bonding initiatives to facilitate mentees' social orientation`,
      `Supporting mentees during stretches of psychosocial and medical hardship`,
      `Attending mentorship meetings to share headway, concerns, and details regarding upcoming mentorship events`,
      `Reporting all pressing concerns for in-depth review`,
    ],
    [
      `Empowering emerging adults with their growth and development`,
      `Innovating the movement towards mental wellness`,
      `Collaboration with multi-disciplinary senior board members`,
      `Growing your professional network`,
      `Room for advancement and growth within the organization to serve as a board member`,
    ],
    [
      `Able to work remotely`,
      `Ambitious and dedicated`,
      `Someone who embodies our core values and represents the organization in their manner and personality`,
      `Someone who is approachable and makes the mentee feel comfortable`,
      `Should be well aware and knowledgeable to help out the mentee`,
      `Gives reassurance, is respectful and makes the mentee feel safe`,
      `Demonstrable experience as a mentor`,
      `Capacity to actualize all personal commitments`,
      `Ability to perceive psychosocial, medical, and similar difficulties`,
    ],
  ];
  return (
    <div className="container mx-auto lg:mx-48">
      <Head>
        <title>Empowered Futures - Become a Mentor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="font-extrabold text-5xl leading-[4rem]">
        Empowered Futures
        <br />
        Mentorship
      </h1>

      <section className="flex flex-col items-center">
        <div className='w-9/12'>
          <h2 className="font-semibold text-3xl">Description of Role</h2>
          <ul>
            {bullets[0].map((text, i) => {
              return (
                <li key={i} className="text-lg">
                  • {text}
                </li>
              );
            })}
          </ul>
        </div>
      </section>

      <section className="flex flex-col items-center">
        <div className='w-9/12'>
          <h2 className="font-semibold text-3xl">What&apos;s in it for you?</h2>
          <ul>
            {bullets[1].map((text, i) => {
              return (
                <li key={i} className="text-lg">
                  • {text}
                </li>
              );
            })}
          </ul>
        </div>
      </section>

      <section className="flex flex-col items-center">
        <div className='w-7/12'>
          <h2 className="font-semibold text-3xl">Prerequisite Requirements</h2>
          <ul>
            {bullets[2].map((text, i) => {
              return (
                <li key={i} className="text-lg">
                  • {text}
                </li>
              );
            })}
          </ul>
        </div>
      </section>
    </div>
  );
};

export default becomeAMentor2;
