import type { NextPage } from 'next';
import Head from 'next/head';
import { GetStaticProps } from 'next';

// Statically renders page and sets props equal to an empty object
export const getStaticProps: GetStaticProps = async (context) => {
  return { props: {} };
};
const getInvolved: NextPage = ({}) => {
  return (
    <div>
      <Head>
        <title>Empowered Futures - Get Involved</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Get Involved placeholder</h1>
    </div>
  );
};

export default getInvolved;
