import type { NextPage } from 'next';
import Head from 'next/head';

const getInvolved: NextPage = ({}) => {
  return (
    <div>
      <Head>
        <title>Empowered Futures - Get Involved</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Get Involved placeholder</h1>
    </div>
  );
};

export default getInvolved;
