import type { NextPage } from 'next';
import Head from 'next/head';
import SocialMediaLink from '../components/socialMediaLinks/social-media-link';
import { SocialMedia } from '../enum/SocialMedia.enum';

const Home: NextPage = ({}) => {
  const linkTypes: SocialMedia[] = Object.values(SocialMedia);
  return (
    <div>
      <Head>
        <title>Empowered Futures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home Page - Hello world!</h1>
      <div>
        <div className="flex">
          {linkTypes.map((t, i) => {
            const type = t as SocialMedia;
            return <SocialMediaLink key={i} domain={type} />;
          })}
        </div>
      </div>
    </div>
  );
};

export default Home;
