import React, { useState } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';

import CheckboxFilter from '../components/checkboxFilter/checkbox-filter';
import { FilterOption } from '../interface/filter-option.interface';
import { OptionStatus } from '../interface/option-status.interface';

const Home: NextPage = ({}) => {
  const sections: FilterOption[] = [
    {
      title: 'Gender',
      options: [{ text: 'Male' }, { text: 'Female' }],
    },
    {
      title: 'Skills',
      options: [
        { text: 'Design' },
        { text: 'Business' },
        { text: 'Management' },
        { text: 'Other' },
      ],
    },
    {
      title: 'Goals',
      options: [
        { text: 'Job Advancement' },
        { text: 'Job Search Help' },
        { text: 'Networking' },
        { text: 'Other' },
      ],
    },
    {
      title: 'Geographic Location',
      options: [
        { text: 'Canada' },
        { text: 'United States' },
        { text: 'Other' },
      ],
    },
    {
      title: 'Company',
      options: [
        { text: 'Microsoft' },
        { text: 'Google' },
        { text: 'Netflix' },
        { text: 'Salesforce' },
      ],
    },
  ];

  const filterTestValues = [
    'Microsoft',
    'Canada',
    'United States',
    'Google',
    'Netflix',
    'Design',
    'Business',
    'Male',
    'Female',
  ];

  const [checkboxState, setCheckboxState] = useState<FilterOption[]>(sections);

  function getCheckedFilters(checkboxState: FilterOption[]): string[] {
    const acceptedValues = checkboxState
      .map((section: FilterOption) => {
        return section.options
          .filter((status: OptionStatus) => status.isChecked)
          .map((remaining) => remaining.text);
      })
      .flat();
    return acceptedValues;
  }

  function getFilteredResults(
    rawInputs: string[],
    acceptedValues: string[]
  ): string[] {
    if (acceptedValues.length === 0) return rawInputs;
    return rawInputs.filter((i) => acceptedValues.includes(i));
  }

  return (
    <div>
      <Head>
        <title>Empowered Futures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home Page - Hello world!</h1>
      <div className="flex">
        <CheckboxFilter
          sections={checkboxState}
          reportToState={setCheckboxState}
        />
        {getFilteredResults(
          filterTestValues,
          getCheckedFilters(checkboxState)
        ).map((v, i) => (
          <div key={i} className="mr-3">
            <p>{v} is shown</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Home;
