import type { NextPage } from 'next';
import Head from 'next/head';

const suggestAProgram: NextPage = ({}) => {
  return (
    <div>
      <Head>
        <title>Empowered Futures - Suggest a Program</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Suggest a Program placeholder</h1>
    </div>
  );
};

export default suggestAProgram;
