import type { NextPage } from 'next';
import Head from 'next/head';
import AdminPanelMain from './admin-panel-main';

const adminPanelDashboard: NextPage = ({}) => {
  return (
    <div>
      <Head>
        <title>Empowered Futures - Dashboard </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminPanelMain />
    </div>
  );
};

export default adminPanelDashboard;
